# Generated by Django 4.2.9 on 2024-01-30 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
